// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMigCh9MHVgCN0xMPCn3g6vdGz3iKOuI',
    appId: '1:349595675742:web:af5c70e59be7836890d8cf',
    messagingSenderId: '349595675742',
    projectId: 'ibafall2-689b8',
    authDomain: 'ibafall2-689b8.firebaseapp.com',
    storageBucket: 'ibafall2-689b8.firebasestorage.app',
    measurementId: 'G-HJE3NJ210F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYRjowKZePdxZGzNGbkINCk_LOeEZsCE',
    appId: '1:349595675742:android:852872ef4de1269990d8cf',
    messagingSenderId: '349595675742',
    projectId: 'ibafall2-689b8',
    storageBucket: 'ibafall2-689b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubbHRyqiQguldDGZyxM35Z9yBNITeLjA',
    appId: '1:349595675742:ios:399e710a2fd2464090d8cf',
    messagingSenderId: '349595675742',
    projectId: 'ibafall2-689b8',
    storageBucket: 'ibafall2-689b8.firebasestorage.app',
    iosBundleId: 'com.example.ibaCourse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAubbHRyqiQguldDGZyxM35Z9yBNITeLjA',
    appId: '1:349595675742:ios:1e5cc1613fd0364f90d8cf',
    messagingSenderId: '349595675742',
    projectId: 'ibafall2-689b8',
    storageBucket: 'ibafall2-689b8.firebasestorage.app',
    iosBundleId: 'com.example.ibaCourse2.RunnerTests',
  );
}
